server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/app_db
    username: app_user
    password: app_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

eureka:
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8761/eureka

management:
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
